# Counters

In [2]:
mytext="ot to adopt her: forty dollars. And then I had to buy litter, a litterbox, food, and dishes for her to eat out of. Two days after she came home with me she got taken to the pound by the animal warden. There's a leash law for cats in Fort Collins. If they're not in your yard they have to be on a leash. Anyway, my cat is my best friend. I'm glad I got her. She sleeps under the covers with me when it's cold. Sometimes she meows a lot in the middle of the night and wakes me up, though."

In [3]:
mylist=mytext.split()

In [25]:
import collections
from operator import itemgetter
c=collections.Counter(mylist)
for i,j in sorted(c.items(),key=itemgetter(1),reverse=True):
    print i,j

to 5
the 5
a 4
in 3
me 3
she 3
and 2
for 2
got 2
I 2
with 2
my 2
friend. 1
pound 1
her. 1
sleeps 1
then 1
had 1
is 1
Two 1
covers 1
warden. 1
her: 1
There's 1
I'm 1
meows 1
have 1
litter, 1
home 1
your 1
best 1
out 1
dollars. 1
up, 1
wakes 1
it's 1
Anyway, 1
night 1
of. 1
forty 1
by 1
leash 1
cats 1
animal 1
under 1
taken 1
when 1
Fort 1
buy 1
lot 1
Sometimes 1
on 1
after 1
food, 1
leash. 1
litterbox, 1
She 1
they 1
not 1
be 1
law 1
eat 1
glad 1
And 1
they're 1
yard 1
dishes 1
middle 1
adopt 1
days 1
cat 1
cold. 1
her 1
of 1
ot 1
Collins. 1
though. 1
came 1
If 1


In [26]:
# Dezyre Python basics start here

In [29]:
print 'Hello Radhika!'

Hello Radhika!


In [32]:
#Native types of variables
# str,int,float,bool,complex(1+0.2j,1-5j)
type(1.032),type(True),type('Abhijit')

(float, bool, str)

In [38]:
# int('gagan') will throw an error but int('1') should work
a='1.5'
print(type(float(a)))
print(type(int(float(a))))

<type 'float'>
<type 'int'>


# String Operations

In [39]:
#Replace,Split,Substring
name='My name is Radhika'
name.split()

['My', 'name', 'is', 'Radhika']

In [42]:
name.replace('name',"daughter's name")

My daughter's name is Radhika


In [45]:
#Substring
name[-7:]

'Radhika'

In [46]:
name[0:]

'My name is Radhika'

In [51]:
name[0:1] # selects everything but object in index[1]

'M'

In [53]:
name[5:5]

''

In [55]:
name[::2] #Selects every element + 2nd element +4th elemeny

'M aei ahk'

In [56]:
name[::-1] # Reverses the string

'akihdaR si eman yM'

In [67]:
# find out about sort function

# List Operations

In [70]:
#append,remove,del,sort,count
a=[1,2,'rad'] # collection of objects
# Also retains the ORDER of the variables that they came in
a

[1, 2, 'rad']

In [72]:
a.append('1.034')
a

[1, 2, 'rad', '1.034', '1.034']

In [74]:
a.remove('1.034') # Removing based on values
a

[1, 2, 'rad']

In [76]:
del a[0]                  # Removing by index
a

['rad']

# Dictionary Operations

In [77]:
mydict={
    'name':'Radhika',
    'score':'100',
    'dad':'Abhijit'
}

In [78]:
del mydict['score']

In [79]:
mydict

{'dad': 'Abhijit', 'name': 'Radhika'}

In [81]:
mydict['score']='100'
mydict

{'dad': 'Abhijit', 'name': 'Radhika', 'score': '100'}

In [82]:
print(mydict.items())
print(mydict.keys())
print(mydict.values())

[('dad', 'Abhijit'), ('score', '100'), ('name', 'Radhika')]
['dad', 'score', 'name']
['Abhijit', '100', 'Radhika']


In [85]:
#Sort a list by values
from operator import itemgetter
for i,j in sorted(mydict.items(),key=itemgetter(1)):
    print i,':',j

score : 100
dad : Abhijit
name : Radhika


In [87]:
# Sort a list of dicts
Grab from hackernews program

SyntaxError: invalid syntax (<ipython-input-87-71f8a05ff6f9>, line 2)

In [90]:
#list comprehension and Dict comprehensions - Look from cheatsheet
even_numbers = [x for x in range(5) if x % 2 == 0]
pairs = [(x, y)
         for x in range(10)
         for y in range(10)]

# Numpy

In [1]:
import numpy as np

In [2]:
#Create an array
np.array([12,13,14])

array([12, 13, 14])

In [3]:
# Array has to have same data type. Lists can have any types of objects. Same type of data types in arrays 
#helps with performance
# in array, length of axis needs to be same

In [7]:
# np.ones((shape))     Shape needs to be a tuple
np.ones((3,4,2))

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [8]:
# np.zeroes((shape))

In [9]:
np.eye(3) # If you multiply any matrix to this matrix, you get the original matrix ...similar to multiplying any 
# number by 1

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [18]:
a=np.array( [[123,456,789],[1,2,3]],dtype=np.float64)

In [12]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).

In [20]:
a

array([[ 123.,  456.,  789.],
       [   1.,    2.,    3.]])

In [21]:
a.ravel()

array([ 123.,  456.,  789.,    1.,    2.,    3.])

In [22]:
a.flatten()

array([ 123.,  456.,  789.,    1.,    2.,    3.])

In [27]:
x=np.array( [[1,2],[5,6]],dtype=np.float64 )
y=np.array( [[10,20],[50,60]],dtype=np.float64 )
x,y

(array([[ 1.,  2.],
        [ 5.,  6.]]), array([[ 10.,  20.],
        [ 50.,  60.]]))

In [25]:
#add,subtract,divide,sqrt,dot
print np.add(x,y)
print np.subtract(x,y)
print np.divide(y,x)

[[ 11.  22.]
 [ 55.  66.]]
[[ -9. -18.]
 [-45. -54.]]
[[ 10.  10.]
 [ 10.  10.]]


In [28]:
#Broadcast Functionality
w= np.array( [[1,2],[3,4],[5,6]] )
z= np.array( [[7,8]] )
print np.add(w,z)

[[ 8 10]
 [10 12]
 [12 14]]


In [29]:
#Dot is matrix multiplication. Broadcast functionality doesnt work with dot

In [31]:
# Conditional statements
if 2<5:
    print 'great'
elif 3>5:
    print 'not great'
else:
    print 'greater than 10'

great


# Loops

In [35]:
from __future__ import print_function
a=[1,2,3,4]
for i in a:
    print(i,end='')

1234

In [59]:
word='Super Excited'
index=0
letter=word[index]
while letter != 'i':
    index=index+1
    letter=word[index]
print(index)

9


# List Comprehensions

In [36]:
list=[x for x in range(11)]

In [37]:
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
mylist=[x for x in range(10) if x%3==0]

In [40]:
mylist

[0, 3, 6, 9]

In [42]:
myotherlist=[x if x%3==0 else 0 for x in range(10)]

In [43]:
myotherlist

[0, 0, 0, 3, 0, 0, 6, 0, 0, 9]

# Functions

In [60]:
def sum(a,b,c):
    return a+b+c

In [61]:
sum(1,2,3)

6