![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide1.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide2.JPG)

In [1]:
x = "i am a data enthusiast"

In [2]:
print x

i am a data enthusiast


![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide3.JPG)

In [6]:
#PyPy
#CPython
#IPython
#Jython
#Cython
#Pyston

#mayavi
#VTK wrapper

In [10]:
help(open)

Help on built-in function open in module __builtin__:

open(...)
    open(name[, mode[, buffering]]) -> file object
    
    Open a file using the file() type, returns a file object.  This is the
    preferred way to open a file.  See file.__doc__ for further information.



In [11]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setslice__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [12]:
help(list.append)

Help on method_descriptor:

append(...)
    L.append(object) -- append object to end



![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide4.JPG)

In [ ]:
# built-in data type
bool- No, True/False - boolean
bytes- No, 
dict{:}, Yes, {'mr A': data scientist, 'Mr B': doctor}
float
int
list[]
set{}
slice :
str 
tuple(,)

In [6]:
# numpy data types
import numpy as np
import pandas as pd

In [7]:
# array
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]])

In [8]:
# matrix
np.matrix([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

matrix([[ 1,  2, 23,  4, 56, 78, 32],
        [21, 34, 54, 67, 76, 89, 90]])

In [13]:
# bool_
np.array([[1,2,23,0,56,78,32],
        [21,34,54,67,76,89,90]],"bool_")

array([[ True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]], dtype=bool)

In [8]:
# array
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]])

In [9]:
# matrix
np.matrix([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

matrix([[ 1,  2, 23,  4, 56, 78, 32],
        [21, 34, 54, 67, 76, 89, 90]])

In [10]:
# bool_
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],"bool_")

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]], dtype=bool)

In [14]:
# int_
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]])

In [15]:
# int8
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],"b")


array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]], dtype=int8)

In [16]:
# int16
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'h')

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]], dtype=int16)

In [17]:
# int32
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'i')

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]], dtype=int32)

In [18]:
# int64
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'l')

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]])

In [16]:
# float_
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'float_')

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]])

In [17]:
np.array([[1,2,23,4.,56,78,32],
        [21,34,54,67,76,89,90]])

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]])

In [18]:
# float16
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'e')

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]], dtype=float16)

In [19]:
# float32
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'f')

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]], dtype=float32)

In [20]:
# float64
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'d')

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]])

In [21]:
# float128
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'g')

array([[ 1.0,  2.0,  23.0,  4.0,  56.0,  78.0,  32.0],
       [ 21.0,  34.0,  54.0,  67.0,  76.0,  89.0,  90.0]], dtype=float128)

In [22]:
# complex_
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],'complex_')

array([[  1.+0.j,   2.+0.j,  23.+0.j,   4.+0.j,  56.+0.j,  78.+0.j,
         32.+0.j],
       [ 21.+0.j,  34.+0.j,  54.+0.j,  67.+0.j,  76.+0.j,  89.+0.j,
         90.+0.j]])

In [ ]:
# Assignment
# create 1 arrary each by using
# Text data
# Numeric Data (float)
# Integer Data
# Try converting an integer array to float array

In [23]:
# matrix
np.array([["i","am","a","data","geek"],
        ["looking","forward","to","learn","machine","learning"]])

array([['i', 'am', 'a', 'data', 'geek'],
       ['looking', 'forward', 'to', 'learn', 'machine', 'learning']], dtype=object)

In [25]:
# float
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]],"float_")

array([[  1.,   2.,  23.,   4.,  56.,  78.,  32.],
       [ 21.,  34.,  54.,  67.,  76.,  89.,  90.]])

In [26]:
# integer
np.array([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])

array([[ 1,  2, 23,  4, 56, 78, 32],
       [21, 34, 54, 67, 76, 89, 90]])

In [27]:
np.NaN

nan

In [19]:
# pandas data type
import pandas as pd

In [25]:
# series
df = pd.Series([[1,2,23,4,56,78,32],
        [21,34,54,67,76,89,90]])
df.shape

(2,)

In [30]:
# series - one dimensional
pd.Series([1,2,23,4,56,78,32, 21,34,54,67,76,89,90])

0      1
1      2
2     23
3      4
4     56
5     78
6     32
7     21
8     34
9     54
10    67
11    76
12    89
13    90
dtype: int64

In [32]:
# data frame
df=pd.DataFrame([[1.,2,23,4,56,78,32],
        [21,34,54,67,76,89,90],
             ["i","am","a","data","geek","go","go"],
             [  1.+0.j,   2.+0.j,  23.+0.j,   4.+0.j,  56.+0.j,  78.+0.j,
         32.+0.j]])
df[0][0]

1.0

In [38]:
#df.values
df.head()

0       1        2       3        4        5        6
0       1       2       23       4       56       78       32
1      21      34       54      67       76       89       90
2       i      am        a    data     geek       go       go
3  (1+0j)  (2+0j)  (23+0j)  (4+0j)  (56+0j)  (78+0j)  (32+0j)

In [37]:
# Panel
pd.Panel([[[1,2,23,4,56,78,32,21,34,54,67,76,89,90]]])

<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 1 (major_axis) x 14 (minor_axis)
Items axis: 0 to 0
Major_axis axis: 0 to 0
Minor_axis axis: 0 to 13

In [56]:
df=pd.read_csv("test.csv",sep=" ")
df

0.00632  Unnamed: 1  18.00  Unnamed: 3  Unnamed: 4  2.310  \
NaN 0.02731      NaN         NaN      0         NaN         NaN   7.07   
    0.02729      NaN         NaN      0         NaN         NaN   7.07   
    0.03237      NaN         NaN      0         NaN         NaN   2.18   
    0.06905      NaN         NaN      0         NaN         NaN   2.18   
    0.02985      NaN         NaN      0         NaN         NaN   2.18   
    0.08829      NaN        12.5    NaN         NaN        7.87    NaN   
    0.14455      NaN        12.5    NaN         NaN        7.87    NaN   
    0.21124      NaN        12.5    NaN         NaN        7.87    NaN   
    0.17004      NaN        12.5    NaN         NaN        7.87    NaN   
    0.22489      NaN        12.5    NaN         NaN        7.87    NaN   
    0.11747      NaN        12.5    NaN         NaN        7.87    NaN   
    0.09378      NaN        12.5    NaN         NaN        7.87    NaN   

             Unnamed: 6   0  Unnamed: 8  0.5380  ...    Unnamed: 19  296.0  \
NaN 0.02731         NaN   0         NaN   0.469  ...            NaN  242.0   
    0.02729         NaN   0         NaN   0.469  ...            NaN  242.0   
    0.03237         NaN   0         NaN   0.458  ...            NaN  222.0   
    0.06905         NaN   0         NaN   0.458  ...            NaN  222.0   
    0.02985         NaN   0         NaN   0.458  ...            NaN  222.0   
    0.08829           0 NaN       0.524     NaN  ...            311    NaN   
    0.14455           0 NaN       0.524     NaN  ...            311    NaN   
    0.21124           0 NaN       0.524     NaN  ...            NaN   15.2   
    0.17004           0 NaN       0.524     NaN  ...            311    NaN   
    0.22489           0 NaN       0.524     NaN  ...            311    NaN   
    0.11747           0 NaN       0.524     NaN  ...            311    NaN   
    0.09378           0 NaN       0.524     NaN  ...            311    NaN   

             Unnamed: 21   15.30  396.90  Unnamed: 24  Unnamed: 25   4.98  \
NaN 0.02731          NaN   17.80  396.90          NaN          NaN   9.14   
    0.02729          NaN   17.80  392.83          NaN          NaN   4.03   
    0.03237          NaN   18.70  394.63          NaN          NaN   2.94   
    0.06905          NaN   18.70  396.90          NaN          NaN   5.33   
    0.02985          NaN   18.70  394.12          NaN          NaN   5.21   
    0.08829        15.20  395.60     NaN        12.43          NaN  22.90   
    0.14455        15.20  396.90     NaN        19.15          NaN  27.10   
    0.21124       386.63     NaN   29.93          NaN         16.5    NaN   
    0.17004        15.20  386.71     NaN        17.10          NaN  18.90   
    0.22489        15.20  392.52     NaN        20.45          NaN  15.00   
    0.11747        15.20  396.90     NaN        13.27          NaN  18.90   
    0.09378        15.20  390.50     NaN        15.71          NaN  21.70   

             Unnamed: 27  24.00  
NaN 0.02731          NaN   21.6  
    0.02729          NaN   34.7  
    0.03237          NaN   33.4  
    0.06905          NaN   36.2  
    0.02985          NaN   28.7  
    0.08829          NaN    NaN  
    0.14455          NaN    NaN  
    0.21124          NaN    NaN  
    0.17004          NaN    NaN  
    0.22489          NaN    NaN  
    0.11747          NaN    NaN  
    0.09378          NaN    NaN  

[12 rows x 29 columns]

In [41]:
pd.Panel([[[1,2,23,4,56,78,32,21,34,54,67,76,89,90]]])

<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 1 (major_axis) x 14 (minor_axis)
Items axis: 0 to 0
Major_axis axis: 0 to 0
Minor_axis axis: 0 to 13

In [60]:
# panel4d
dd = pd.Panel4D([[[[1,2,23,4,56,78,32,21,34,54,67,76,89,90]]]],dtype=str)
dd.axes

[Int64Index([0], dtype='int64'),
 Int64Index([0], dtype='int64'),
 Int64Index([0], dtype='int64'),
 Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], dtype='int64')]

In [63]:
dd.

<bound method Panel4D.get_values of <class 'pandas.core.panelnd.Panel4D'>
Dimensions: 1 (labels) x 1 (items) x 1 (major_axis) x 14 (minor_axis)
Labels axis: 0 to 0
Items axis: 0 to 0
Major_axis axis: 0 to 0
Minor_axis axis: 0 to 13>

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide5.JPG)

In [39]:
3+4, 5-3, 4*5, 18/4

(7, 2, 20, 4)

In [6]:
18./5, 18/5

(3.6, 3)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide6.JPG)

In [9]:
12 & 13-4

8

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide7.JPG)

In [46]:
# strings operation
s = 'data science'
t = "data science"
t == s
u = """data science"""
t == u
s == u

True

In [10]:
# dictionary operation
dict(a=12,b=23)

{'a': 12, 'b': 23}

In [11]:
a = {1: 'Monday',2: 'Tuesday',3: 'wednessday'}
print a

{1: 'Monday', 2: 'Tuesday', 3: 'wednessday'}


In [12]:
b = dict()

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide8.JPG)

In [42]:
a = range(20)
print a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [45]:
b = [2]*10
print b

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [46]:
c = []
c.append(11),c.append(12),c.append(13),c.remove(13)
print c

[11, 12]


In [47]:
a.sort()
print a[::-1]

[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [48]:
mixed = ["me",21,True,23.9]
print mixed
mixed[0],mixed[3]
type(mixed[1]),type(mixed[0]),type(mixed[3])

['me', 21, True, 23.9]


(int, str, float)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide9.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide10.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide11.JPG)

In [65]:
print a


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [66]:
print a[0:5]


[0, 1, 2, 3, 4]


In [70]:
print a[::-1]


[19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [68]:
print a[-5:]


[15, 16, 17, 18, 19]


In [69]:
print a[:-6:-1]

[19, 18, 17, 16, 15]


In [54]:
a = [[1,2,3,4],[3,4,5,6,7],['ram','sham']]
print a[2][1]

sham


![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide11.JPG)

In [49]:
import pandas as pd
import nltk as nl

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide12.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide13.JPG)

In [50]:
L = list(range(10))
type(L[0]),type(L)
print L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [63]:
L2 = [str(c) for c in L]
print L2
type(L2),type(L2[3])

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


(list, str)

In [66]:
L3 = [True, "2", 3.0, 4]
print L3
[type(item) for item in L3]

[True, '2', 3.0, 4]


[bool, str, float, int]

In [51]:
import array
print L
A = array.array("i",L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [70]:
import numpy as np

In [74]:
np.array([1,2,3,4,"NA"])

array(['1', '2', '3', '4', 'NA'], 
      dtype='|S21')

In [75]:
np.array([1,2,3,4,12.3])

array([  1. ,   2. ,   3. ,   4. ,  12.3])

In [76]:
np.array([1,2,3,4,12.3],dtype="float32")

array([  1.        ,   2.        ,   3.        ,   4.        ,  12.30000019], dtype=float32)

In [52]:
np.array([range(i,i+3) for i in [2,4,6]]) # two dimensional array

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [53]:
np.zeros((3,5),dtype=int)

# create 3x5 floating point array filled with ones
#np.ones((3,5),dtype=float)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [84]:
# Assignment
# 1- create 5x3 array filled with a value 786
np.full((5,3),786)
# 2- create an array filled with a linear sequence starting at 0, ending at 20 and stepping by 2
np.arange(0,20,2)
# 3- create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)
# 4- create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))
np.random.normal(0,1,(3,3))

array([[-1.53471919,  0.55759698,  1.03911697],
       [ 1.47666387, -1.45782582, -0.92939743],
       [ 1.47291602, -0.75657788,  0.29617905]])

In [85]:
np.random.randint(0,10,(3,3))

array([[0, 6, 3],
       [4, 1, 6],
       [7, 3, 2]])

In [87]:
# create an identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide14.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide15.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide16.JPG)

In [56]:
s1 =45
if (s1<=40):
    print("fail")
else:
    print("pass")

pass


![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide17.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide18.JPG)

In [57]:
# anonymous function - lambda
#f(x) = 3x^2 + 2x - 2
f = lambda x: 3*x**2 + 2*x - 2
f(30)

2758

In [58]:
def polynomial(a, b, c):
    f = lambda x: a*x**2 + b*x + c
    return f

In [59]:
polynomial(3,2,4)

<function __main__.<lambda>>

In [98]:
name = " i am a data scientist"
vowel = ["a","e","i","o","u"]

for letter in name:
    if letter in vowel:
        print letter

i
a
a
a
a
i
e
i


![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide19.JPG)

In [60]:
print range(10)
sum10 = 0;

for i in range(10):
    sum10 = sum10 + (i+1)
print sum10
    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
55


![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide20.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide21.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide22.JPG)

In [61]:
word = 'super excited'
ind = 0;
letter = word[ind];
while letter != 'i':
    letter = word[ind]
    ind = ind + 1
print "Index of First i"
print ind

Index of First i
10


In [62]:
import math


![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide23.JPG)

![image](https://s3.amazonaws.com/dspython.dezyre.com/notebook_files/DS_Python/module1_v1/Slide24.JPG)

In [111]:
# Tha basics of Numpy Array
import numpy as np
np.random.seed(0) # seed is used for reproducibility of the results

x1 = np.random.randint(10, size =6)
x1

array([5, 0, 3, 3, 7, 9])

In [63]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[1, 2, 6, 3],
       [5, 9, 5, 7],
       [7, 9, 9, 1]])

In [64]:
x3 = np.random.randint(10,size=(3,4,5))
x3

array([[[0, 3, 0, 0, 8],
        [7, 6, 3, 4, 5],
        [5, 0, 1, 4, 3],
        [8, 8, 0, 3, 6]],

       [[8, 5, 9, 5, 5],
        [1, 9, 6, 5, 6],
        [0, 4, 8, 8, 2],
        [2, 9, 3, 2, 6]],

       [[1, 6, 7, 9, 9],
        [3, 8, 6, 7, 6],
        [7, 2, 3, 1, 6],
        [9, 0, 1, 1, 9]]])

In [115]:
print("x3 ndim", x3.ndim)

('x3 ndim', 3)


In [116]:
print("shape",x3.shape)

('shape', (3, 4, 5))


In [117]:
print("size",x3.size)

('size', 60)


In [118]:
print("type of data",x3.dtype)

('type of data', dtype('int64'))


In [119]:
print("itemsize",x3.itemsize,"bytes")

('itemsize', 8, 'bytes')


In [120]:
print("nbytes:",x3.nbytes,"bytes")

('nbytes:', 480, 'bytes')


In [121]:
x1

array([5, 0, 3, 3, 7, 9])

In [122]:
x1[4]

7

In [124]:
x1[-3]

3

In [125]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [127]:
x2[2,2]

7

In [128]:
x2[2,-1]

7

In [130]:
x2[1,2] =12

In [131]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 12,  8],
       [ 1,  6,  7,  7]])

In [132]:
x2[2,-1]=15

In [133]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 12,  8],
       [ 1,  6,  7, 15]])

In [134]:
x1

array([5, 0, 3, 3, 7, 9])

In [135]:
x1[0]= 4.12334566

In [136]:
x1

array([4, 0, 3, 3, 7, 9])

In [137]:
# sub-arrays
# x[start:stop:step]

In [138]:
x1

array([4, 0, 3, 3, 7, 9])

In [139]:
x1[:5]

array([4, 0, 3, 3, 7])

In [140]:
x1[5:]

array([9])

In [141]:
x1[4:7]

array([7, 9])

In [143]:
x1[::2] # step here shows every second element

array([4, 3, 7])

In [144]:
x1[1::2]

array([0, 3, 9])

In [145]:
x1[::-1]

array([9, 7, 3, 3, 0, 4])

In [146]:
# assignment: from x2, a two dimensional array extract the following elements
# two rows and three columns
# all rows, every other column


In [147]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 12,  8],
       [ 1,  6,  7, 15]])

In [148]:
x2[:2,:3]

array([[ 3,  5,  2],
       [ 7,  6, 12]])

In [149]:
x2[:3,::2]

array([[ 3,  2],
       [ 7, 12],
       [ 1,  7]])

In [150]:
x2[::-1,::-1]

array([[15,  7,  6,  1],
       [ 8, 12,  6,  7],
       [ 4,  2,  5,  3]])

In [151]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6, 12,  8],
       [ 1,  6,  7, 15]])

In [152]:
print(x2[:,0])

[3 7 1]


In [153]:
print(x2[0,:])

[3 5 2 4]


In [155]:
print(x2)

[[ 3  5  2  4]
 [ 7  6 12  8]
 [ 1  6  7 15]]


In [159]:
x2_sub= x2[:2,:2]
print(x2_sub)

[[3 5]
 [7 6]]


In [160]:
x2_sub[0,0]=99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [161]:
x2

array([[99,  5,  2,  4],
       [ 7,  6, 12,  8],
       [ 1,  6,  7, 15]])

In [162]:
x2_sub_copy = x2[:2,:2].copy()

In [163]:
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [164]:
x2_sub_copy[0,0] = 9999

In [165]:
print(x2_sub_copy)

[[9999    5]
 [   7    6]]


In [166]:
print(x2)

[[99  5  2  4]
 [ 7  6 12  8]
 [ 1  6  7 15]]


In [167]:
# reshaping of arrays

In [180]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [181]:
# concatenation or splitting of arrays

In [183]:
x = np.array([11,32,43,54])
y = np.array([32,34,35,31])
np.concatenate([x,y])

array([11, 32, 43, 54, 32, 34, 35, 31])

In [184]:
z = [98,97,96,95]

In [185]:
np.concatenate([x,y,z])

array([11, 32, 43, 54, 32, 34, 35, 31, 98, 97, 96, 95])

In [186]:
x2

array([[99,  5,  2,  4],
       [ 7,  6, 12,  8],
       [ 1,  6,  7, 15]])

In [187]:
np.concatenate([x2,x2])

array([[99,  5,  2,  4],
       [ 7,  6, 12,  8],
       [ 1,  6,  7, 15],
       [99,  5,  2,  4],
       [ 7,  6, 12,  8],
       [ 1,  6,  7, 15]])

In [188]:
np.concatenate([x2,x2],axis=1)

array([[99,  5,  2,  4, 99,  5,  2,  4],
       [ 7,  6, 12,  8,  7,  6, 12,  8],
       [ 1,  6,  7, 15,  1,  6,  7, 15]])