In [1]:
import os
import numpy as np
import pandas as pd

from sklearn import tree

In [2]:
from sklearn.datasets import load_iris
from sklearn import tree

In [3]:
iris = load_iris()

In [4]:
iris.data.shape # input data

(150, 4)

In [5]:
print iris.DESCR

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:
    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================
    :Missing Attribute Values: None
    

In [6]:
iris.feature_names # getting the feature names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.target.shape # target variable or dependent variable

(150,)

In [8]:
mytree = tree.DecisionTreeClassifier()
mytree

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

In [9]:
mytree = tree.DecisionTreeClassifier(criterion='entropy')
mytree

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

In [10]:
dt1 = mytree.fit(iris.data, iris.target)
dt1

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

In [11]:
dt1.feature_importances_

array([ 0.02317521,  0.        ,  0.64544598,  0.33137881])

In [63]:
# three methods determine the importance of features
# 1. mean decrease in gini coefficient
# 2. informtion gain -cross entropy
# 3. variance based approach

In [64]:
dt1.score(iris.data,iris.target)

1.0

In [12]:
# decision tree for regression based problems
from sklearn.datasets import load_boston
from sklearn.cross_validation import cross_val_score
from sklearn.tree import DecisionTreeRegressor


In [13]:
boston = load_boston()
regressor = DecisionTreeRegressor(random_state=0)
cross_val_score(regressor, boston.data, boston.target, cv=10)

array([ 0.43406909,  0.55245341, -1.55948714,  0.3800447 ,  0.78608642,
        0.509715  ,  0.12765843,  0.35462482, -2.39361224,  0.12732401])

In [14]:
from sklearn.grid_search import GridSearchCV
from time import time
from operator import itemgetter

In [15]:
# create a function to perform grid search with cross validation and returns the accuracy values
def GridSearch_BestParam(X, y, clf, param_grid,cv=10):
    grid_search = GridSearchCV(clf,
                              param_grid=param_grid,
                              cv=cv)
    start= time()
    grid_search.fit(X,y)
    top_params=grid_search.grid_scores_
    return top_params

In [16]:
param_grid = {"criterion": ["gini","entropy"],
             "min_samples_split": [2,10,20],
             "max_depth": [2,5,10],
             "min_samples_leaf":[1,2,10]}

In [17]:
cvDT = tree.DecisionTreeClassifier()

In [18]:
top_para = GridSearch_BestParam(iris.data, iris.target, cvDT, param_grid, cv=10)
print top_para

[mean: 0.95333, std: 0.05207, params: {'min_samples_split': 2, 'criterion': 'gini', 'max_depth': 2, 'min_samples_leaf': 1}, mean: 0.95333, std: 0.05207, params: {'min_samples_split': 10, 'criterion': 'gini', 'max_depth': 2, 'min_samples_leaf': 1}, mean: 0.95333, std: 0.05207, params: {'min_samples_split': 20, 'criterion': 'gini', 'max_depth': 2, 'min_samples_leaf': 1}, mean: 0.95333, std: 0.05207, params: {'min_samples_split': 2, 'criterion': 'gini', 'max_depth': 2, 'min_samples_leaf': 2}, mean: 0.95333, std: 0.05207, params: {'min_samples_split': 10, 'criterion': 'gini', 'max_depth': 2, 'min_samples_leaf': 2}, mean: 0.94667, std: 0.04989, params: {'min_samples_split': 20, 'criterion': 'gini', 'max_depth': 2, 'min_samples_leaf': 2}, mean: 0.94667, std: 0.04989, params: {'min_samples_split': 2, 'criterion': 'gini', 'max_depth': 2, 'min_samples_leaf': 10}, mean: 0.95333, std: 0.05207, params: {'min_samples_split': 10, 'criterion': 'gini', 'max_depth': 2, 'min_samples_leaf': 10}, mean: 0.

In [19]:
top_score = sorted(top_para,key=itemgetter(1), reverse=True)
top_score

[mean: 0.96000, std: 0.04422, params: {'min_samples_split': 2, 'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 1},
 mean: 0.96000, std: 0.03266, params: {'min_samples_split': 10, 'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 1},
 mean: 0.96000, std: 0.03266, params: {'min_samples_split': 20, 'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 1},
 mean: 0.96000, std: 0.03266, params: {'min_samples_split': 2, 'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 2},
 mean: 0.96000, std: 0.03266, params: {'min_samples_split': 10, 'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 2},
 mean: 0.96000, std: 0.03266, params: {'min_samples_split': 20, 'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 2},
 mean: 0.96000, std: 0.03266, params: {'min_samples_split': 10, 'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 1},
 mean: 0.96000, std: 0.03266, params: {'min_samples_split': 20, 'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 1},


In [20]:
paramCV = top_score[0].parameters
paramCV

{'criterion': 'gini',
 'max_depth': 5,
 'min_samples_leaf': 1,
 'min_samples_split': 2}

In [21]:
best_model = tree.DecisionTreeClassifier(max_depth=5,min_samples_split=2,min_samples_leaf=1,criterion='gini')
best_model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

In [22]:
best_model = tree.DecisionTreeClassifier(max_depth=paramCV['max_depth'], min_samples_split=paramCV['min_samples_split'],
                                    min_samples_leaf=paramCV['min_samples_leaf'],
                                   criterion=paramCV['criterion'])
best_model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

In [23]:
best_model.fit(iris.data, iris.target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best')

In [24]:
YValid_Pred = best_model.predict(iris.data) # use XTest, XValid to generate prediction
YValid_Pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
from sklearn import metrics
print metrics.confusion_matrix(iris.target,YValid_Pred)

[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]


In [26]:
best_model.feature_importances_

array([ 0.01333333,  0.        ,  0.56405596,  0.42261071])

In [29]:
################Random Forest Model########################
import sklearn.ensemble as ske
irisRF = ske.RandomForestClassifier(n_estimators=100, max_features='sqrt').fit(iris.data,iris.target)
irisRF

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [30]:
YTestProb = irisRF.predict_proba(iris.data)

YPred = irisRF.predict(iris.data)

print metrics.confusion_matrix(YPred,iris.target)

print metrics.classification_report(YPred,iris.target)

[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       1.00      1.00      1.00        50
          2       1.00      1.00      1.00        50

avg / total       1.00      1.00      1.00       150



In [31]:
irisRF.score(iris.data,iris.target)


1.0

In [32]:
param_grid = {'criterion':['gini','entropy'],
             'min_samples_split':[2,10,15],
             'max_depth': [None,2, 5, 10],
             'min_samples_leaf':[1,2],
             'max_features': [2,3]
             }

In [33]:
cvRF = ske.RandomForestClassifier(n_estimators=10)

In [35]:
cvRF_Param = GridSearch_BestParam(iris.data,iris.target,cvRF, param_grid,cv=10)


In [36]:
cvRF_Param

[mean: 0.95333, std: 0.04269, params: {'max_features': 2, 'min_samples_split': 2, 'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1},
 mean: 0.96667, std: 0.03333, params: {'max_features': 2, 'min_samples_split': 10, 'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1},
 mean: 0.96667, std: 0.03333, params: {'max_features': 2, 'min_samples_split': 15, 'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1},
 mean: 0.94667, std: 0.06532, params: {'max_features': 2, 'min_samples_split': 2, 'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 2},
 mean: 0.96667, std: 0.03333, params: {'max_features': 2, 'min_samples_split': 10, 'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 2},
 mean: 0.95333, std: 0.06000, params: {'max_features': 2, 'min_samples_split': 15, 'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 2},
 mean: 0.97333, std: 0.03266, params: {'max_features': 3, 'min_samples_split': 2, 'criterion': 'gini', 'max_depth': None

In [37]:
paramCV = sorted(cvRF_Param,key=itemgetter(1), reverse=True)

In [38]:
paramCV = paramCV[0].parameters

In [40]:
paramCV

{'criterion': 'gini',
 'max_depth': None,
 'max_features': 3,
 'min_samples_leaf': 1,
 'min_samples_split': 2}

In [41]:
cvRF = ske.RandomForestClassifier(n_estimators=100,criterion=paramCV["criterion"],max_depth=paramCV["max_depth"],
                                  max_features=paramCV["max_features"],
                                min_samples_split=paramCV["min_samples_split"],
                                  min_samples_leaf=paramCV["min_samples_leaf"])

cvRF.fit(iris.data, iris.target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=3, max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [42]:
YValidRF = cvRF.predict(iris.data)

print metrics.confusion_matrix(iris.target,YValidRF)

[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]


In [43]:
cvRF.score(iris.data, iris.target)

1.0

In [44]:
cvRF.feature_importances_

array([ 0.01574406,  0.0133037 ,  0.51013893,  0.46081331])

In [45]:
best_model.feature_importances_

array([ 0.01333333,  0.        ,  0.56405596,  0.42261071])

In [ ]:
# How the GB model works:
# a loss function
# a weak learner to make predictions/classifications
# an additive model to add weak learners to minimize the loss function

In [ ]:
# Loss functions: it should be differentiable
# for regression based tasks the loss function should be squared error
# for classification based tasks the loss function should be logarithimic loss

In [ ]:
# learner
# consider all the features are weak learners, greedy manner
# 

In [46]:
##########Gradient Boosting model############
import sklearn.ensemble as ske
irisRF = ske.GradientBoostingClassifier(n_estimators=100).fit(iris.data,iris.target)
irisRF

GradientBoostingClassifier(init=None, learning_rate=0.1, loss='deviance',
              max_depth=3, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [47]:
irisRF.score(iris.data,iris.target)

1.0

In [48]:
param_grid = {'loss' : ['deviance'],
             'learning_rate':[0.1,0.2,0.3]
             }

In [49]:
cvGB = ske.GradientBoostingClassifier(n_estimators=50)

In [50]:
cvGB_Param = GridSearch_BestParam(iris.data,iris.target,cvGB, param_grid,cv=10)

In [51]:
paramCV = sorted(cvGB_Param,key=itemgetter(1), reverse=True)
paramCV

[mean: 0.96000, std: 0.04422, params: {'loss': 'deviance', 'learning_rate': 0.1},
 mean: 0.96000, std: 0.04422, params: {'loss': 'deviance', 'learning_rate': 0.2},
 mean: 0.96000, std: 0.04422, params: {'loss': 'deviance', 'learning_rate': 0.3}]

In [52]:
cvGB.fit(iris.data,iris.target)

GradientBoostingClassifier(init=None, learning_rate=0.1, loss='deviance',
              max_depth=3, max_features=None, max_leaf_nodes=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=50,
              random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [53]:
YValidGB = cvGB.predict(iris.data)

In [56]:
print metrics.confusion_matrix(iris.target,YValidGB)

[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]


In [54]:
cvGB.feature_importances_

array([ 0.02893437,  0.11650088,  0.37281977,  0.48174497])

In [ ]:
# improvement in basic gradient boosting model
# penalized learning
# shrinkage (SGD Model)
# tree constraints

In [57]:
#######Support vector Machine################
X = iris.data
Y = iris.target

In [59]:
from sklearn.svm import SVC

In [60]:
model = SVC()

In [61]:
from sklearn.cross_validation import train_test_split

In [62]:
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size=0.4, random_state=1234)

In [63]:
model.fit(X_Train,Y_Train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [64]:
pred = model.predict(X_Test)

In [65]:
print metrics.accuracy_score(Y_Test,pred)

0.983333333333


In [132]:
from sklearn import svm

In [133]:
svm.SVC(kernel="linear",C=1.0).fit(X,Y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [135]:
svm.SVC(kernel="rbf",C=1.0,gamma=0.7).fit(X,Y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.7,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [136]:
svm.SVC(kernel="poly",C=1.0,degree=3).fit(X,Y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [137]:
svm.LinearSVC(C=1.0).fit(X,Y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [ ]:
# merits:
# very effective in high dimension and low samples scenario
# different kernels

# demerits:
# memory intensive algo
# this is not for larger datasets, it takes more time for model convergence
# it does not provie probabilities like standard classifiers